### ISSUE TITLE
what is this issue

### ISSUE THREAD

**Issue by Roybabu** [Cosmic-OS/platform_manifest#14]
; rm -f /home/roybabu/cosmic/out/target/product/condor/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/core/jni/com_android_server_AlarmManagerServic
e.d )"
frameworks/base/services/core/jni/com_android_server_AlarmManagerService.cpp:60:5: error: use of undeclared identifier 'CLOCK_POWEROFF_ALARM'
    CLOCK_POWEROFF_ALARM,
    ^
frameworks/base/services/core/jni/com_android_server_AlarmManagerService.cpp:427:61: error: use of undeclared identifier 'CLOCK_POWEROFF_ALARM'
        if ((fds[i] < 0) && (android_alarm_to_clockid[i] == CLOCK_POWEROFF_ALARM)) {
                                                            ^
2 errors generated.
[ 79% 25851/32581] -e \033[32mtarget thumb C++:\033[0m libandroid_servers <=...orks/base/services/core/jni/com_android_server_am_ActivityManagerService.cpp
frameworks/base/services/core/jni/com_android_server_am_ActivityManagerService.cpp:44:40: warning: unused parameter 'env' [-Wunused-parameter]
    static jint migrateToBoost(JNIEnv *env, jobject _this)
                                       ^
frameworks/base/services/core/jni/com_android_server_am_ActivityManagerService.cpp:44:53: warning: unused parameter '_this' [-Wunused-parameter]
    static jint migrateToBoost(JNIEnv *env, jobject _this)
                                                    ^
frameworks/base/services/core/jni/com_android_server_am_ActivityManagerService.cpp:89:42: warning: unused parameter 'env' [-Wunused-parameter]
    static jint migrateFromBoost(JNIEnv *env, jobject _this)
                                         ^
frameworks/base/services/core/jni/com_android_server_am_ActivityManagerService.cpp:89:55: warning: unused parameter '_this' [-Wunused-parameter]
    static jint migrateFromBoost(JNIEnv *env, jobject _this)
                                                      ^
4 warnings generated.
[ 79% 25851/32581] -e \033[32mtarget thumb C++:\033[0m libandroid_servers <=...meworks/base/services/core/jni/com_android_server_am_BatteryStatsService.cpp
frameworks/base/services/core/jni/com_android_server_am_BatteryStatsService.cpp:65:51: warning: unused parameter 'clazz' [-Wunused-parameter]
static jint nativeWaitWakeup(JNIEnv *env, jobject clazz, jobject outBuf)
                                                  ^
1 warning generated.
[ 79% 25851/32581] -e \033[32mtarget thumb C++:\033[0m libandroid_servers <= frameworks/base/services/core/jni/com_android_server_connectivity_Vpn.cpp
frameworks/base/services/core/jni/com_android_server_connectivity_Vpn.cpp:216:48: warning: unused parameter 'thiz' [-Wunused-parameter]
static bool modifyAddress(JNIEnv *env, jobject thiz, jstring jName, jstring jAddress,
                                               ^
1 warning generated.
[ 79% 25851/32581] -e \033[32mtarget thumb C++:\033[0m libF77blas <= external/eigen/blas/complex_single.cpp
ninja: build stopped: subcommand failed.
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1

**Comment by sagarshah1729** [comment]
@Roybabu This is due to a missing commit in fwb

**Comment by Roybabu** [comment]
how to fix it.

**Comment by imranpopz** [comment]
is this source bug ?

**Comment by AgentFabulous** [comment]
@imranpopz source bug
